### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by somenathmaji** [cjhutto/vaderSentiment#13]
**successful import
platform : windows 7(x64)
python version : 3.5.1**

Traceback (most recent call last):
  File "C:\Users\user\Desktop\sentiment\sentiment2.py", line 2, in <module>
    from vaderSentiment.vaderSentiment import sentiment as vaderSentiment
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 530, in spec_from_file_location
  File "C:\Python\Python35\lib\site-packages\vadersentiment-0.5-py3.5.egg\vaderSentiment\vaderSentiment.py", line 23
    return dict(map(lambda (w, m): (w, float(m)), [wmsr.strip().split('\t')[0:2] for wmsr in open(f) ]))
                           ^
SyntaxError: invalid syntax

**Comment by binlogreader** [comment]
I faced the same challenge. Is there is a work around to it?

I did however found an alternate way of working with vader. It seems NLTK has an inbuilt vader support as well. You can try working with --

from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()
sid.polarity_scores(text)

The question remains, if the two implementation yield different results or not since they both are using the same lexicon, when I compared the source code.

**Comment by ghost** [comment]
having this same problem. Windows 10, Python 3.5

**Comment by rosepog** [comment]
This happens with Python 3.5 version only. This works well on 2.7. How to fix this error with Python 3.5?

**Comment by CloudandReact** [comment]
Having this same error with python 3 anybody if there is a fix now

**Comment by rosepog** [comment]
I changed the return statement to this:

return dict(map(lambda wm: (wm[0], float(wm[1])), [wmsr.strip().split('\t')[0:2] for wmsr in open(f) ]))

**Comment by cjhutto** [comment]
Thanks!  The new update (with new pip install) has better compatibility support for Python 3.
