### ISSUE TITLE
In Python 3.5

### ISSUE THREAD

**Issue by pablofernandezorg** [cjhutto/vaderSentiment#18]
Traceback (most recent call last):
  File "/Users/pablofernandez/Desktop/StockMarket/stocktwits.py", line 37, in <module>
    from vaderSentiment.vaderSentiment import sentiment as vaderSentiment
  File "/Users/pablofernandez/anaconda/lib/python3.5/site-packages/vaderSentiment/vaderSentiment.py", line 20, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by pablofernandezorg** [comment]
resolved for python 3.5
from imp import reload

**Comment by cjhutto** [comment]
Thanks!  The new update has better compatibility support for Python 3.
