### ISSUE TITLE
AttributeError: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by markjrobby** [cjhutto/vaderSentiment#43]
Running on Python 2.7
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    vs = analyzer.polarity_scores(sentence)
  File "/Users/markjrobby/Desktop/feedback/venv/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.py", line 218, in polarity_scores
    sentitext = SentiText(text)
  File "/Users/markjrobby/Desktop/feedback/venv/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.py", line 150, in __init__
    text = str(text.encode('utf-8'))
AttributeError: 'list' object has no attribute 'encode'

Fix that solves the error:
text = str(text).encode('utf-8')

**Comment by cjhutto** [comment]
@markjrobby 
Thanks so much for the heads up and for pointing out the easy solution.

BTW -- I also updated VADER to handle emojis in UTF-8 encoded text... it should be easy to get the latest version using `> pip install --upgrade vaderSentiment`. 

Again, thanks for the input/feedback!
